version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: shopper-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: shopper-challenge
      POSTGRES_DB: shopper
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data